<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ASSANELLI Franco, KUZMINSKI Nicolás">

<title>Informe - Trabajo Práctico Regresión Logística - AyME</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/quarto-html/quarto.js"></script>
<script src="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/quarto-html/popper.min.js"></script>
<script src="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Informe - Trabajo Práctico Regresión Logística - AyME 2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Informe - Trabajo Práctico Regresión Logística - AyME</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ASSANELLI Franco, KUZMINSKI Nicolás </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="cáncer-de-mama" class="level1">
<h1>Cáncer de mama</h1>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<p>Se ha desarrollado un sistema de diagnóstico de tumores de mama mediante técnicas interactivas de procesamiento de imágenes y un clasificador basado en programación lineal. El sistema analiza el tamaño, la forma y la textura del núcleo para calcular diez características para cada núcleo. Al probar diferentes combinaciones de características, el estudio logró una precisión del 94% al distinguir entre muestras benignas y malignas. Unas 569 imágenes se han de procesado de esta manera obteniendo las 10 variables para cada una de ellas. El objetivo de este trabajo es desarrollar un modelo de regresión logística que permita predecir si un tumor es benigno o maligno en base a las variables obtenidas.</p>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>La siguiente base de datos contiene información sobre 569 tumores de mama, de los cuales 357 son benignos y 212 son malignos. Para cada uno de ellos se registraron 32 variables, de las cuales 30 son numéricas y 2 son categóricas. Las variables numéricas son medidas obtenidas a partir de imágenes digitalizadas de los tumores, mientras que las variables categóricas son el diagnóstico (benigno o maligno) y el identificador del paciente. De las 30 variables numéricas, 10 son medidas obtenidas a partir de la media de las imágenes, 10 son medidas obtenidas a partir sus errores estándar y 10 son medidas obtenidas a partir de sus peores valores. Para este trabajo se utilizan las variables obtenidas a partir de la media de las imágenes para desarrollar un modelo de regresión logística que permita explicar la variable categórica <em>diagnóstico</em>.</p>
</section>
<section id="carga-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="carga-de-datos">Carga de datos</h2>
<p>Obtenemos la base de datos de la siguiente dirección: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic. La misma se encuentra comprimida y dentro en formato csv. La cargamos en R y la guardamos en un objeto y mantenemos las variables que nos interesan con nombres más cortos y descriptivos en español.</p>
<p>Aparte, analizamos las variables predictoras que contienen las medias porque resultan más sencillas para comunicar los resultados, y porque expresan con mayor claridad la situación de cada caso. En contraposición, las variables que expresan los errores estándar o los valores límite, resultan más complejas de comunicar o analizar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">"https://archive.ics.uci.edu/static/public/17/breast+cancer+wisconsin+diagnostic.zip"</span>, <span class="st">"data/breast+cancer+wisconsin+diagnostic.zip"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(<span class="st">"data/breast+cancer+wisconsin+diagnostic.zip"</span>, <span class="at">exdir =</span> <span class="st">"data"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>cmama <span class="ot">&lt;-</span> <span class="fu">read.csv</span> (<span class="st">"data/wdbc.data"</span>, <span class="at">header =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>cmama2 <span class="ot">&lt;-</span> cmama [, <span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>)] <span class="co">#Recorte de datos</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span> (cmama2) <span class="ot">&lt;-</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"diagnostico"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"radio_medio"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"textura_media"</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"perimetro_medio"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"area_media"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"uniformidad_media"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"compactabilidad_media"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"concavidad_media"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"puntos_concavos_medios"</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"simetria_media"</span>, </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"dimension_fractal_media"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>cmama2<span class="sc">$</span>diagnostico <span class="ot">&lt;-</span> <span class="fu">ifelse</span> (cmama2<span class="sc">$</span>diagnostico <span class="sc">==</span> <span class="st">"B"</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(cmama2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 569
Columns: 11
$ diagnostico             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ radio_medio             &lt;dbl&gt; 17.990, 20.570, 19.690, 11.420, 20.290, 12.450…
$ textura_media           &lt;dbl&gt; 10.38, 17.77, 21.25, 20.38, 14.34, 15.70, 19.9…
$ perimetro_medio         &lt;dbl&gt; 122.80, 132.90, 130.00, 77.58, 135.10, 82.57, …
$ area_media              &lt;dbl&gt; 1001.0, 1326.0, 1203.0, 386.1, 1297.0, 477.1, …
$ uniformidad_media       &lt;dbl&gt; 0.11840, 0.08474, 0.10960, 0.14250, 0.10030, 0…
$ compactabilidad_media   &lt;dbl&gt; 0.27760, 0.07864, 0.15990, 0.28390, 0.13280, 0…
$ concavidad_media        &lt;dbl&gt; 0.30010, 0.08690, 0.19740, 0.24140, 0.19800, 0…
$ puntos_concavos_medios  &lt;dbl&gt; 0.14710, 0.07017, 0.12790, 0.10520, 0.10430, 0…
$ simetria_media          &lt;dbl&gt; 0.2419, 0.1812, 0.2069, 0.2597, 0.1809, 0.2087…
$ dimension_fractal_media &lt;dbl&gt; 0.07871, 0.05667, 0.05999, 0.09744, 0.05883, 0…</code></pre>
</div>
</div>
<p>Además, definimos la problemática: el criterio de diagnóstico ¿es explicada por las variables vinculadas al tamaño, la textura y la forma del tumor? ¿De que manera?</p>
</section>
<section id="análisis-exploratorio" class="level2">
<h2 class="anchored" data-anchor-id="análisis-exploratorio">Análisis exploratorio</h2>
<p>La variable dependiente es la variable dicotómica <em>diagnóstico</em>, que toma el valor 0 si el tumor es benigno y 1 si el tumor es maligno.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cmama2 <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(diagnostico), <span class="at">fill =</span> <span class="fu">factor</span>(diagnostico))) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Informe---Trabajo-Práctico-Regresión-Logística---AyME-2_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Las 10 variables cuantitativas continuas independientes refieren a medidas de los tumores:</p>
<ol type="a">
<li>radio (media de las distancias desde el centro hasta puntos en el perímetro)</li>
<li>textura (desviación estándar de los valores de escala de grises)</li>
<li>perímetro</li>
<li>área</li>
<li>suavidad o uniformidad (variación local en longitudes de radio)</li>
<li>compacidad (perímetro^2 / área - 1.0)</li>
<li>concavidad (severidad de porciones cóncavas del contorno)</li>
<li>puntos cóncavos (número de porciones cóncavas del contorno)</li>
<li>simetría</li>
<li>dimensión fractal (“aproximación de la línea costera” - 1)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cmama2 <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(<span class="at">key =</span> <span class="st">"variable"</span>, <span class="at">value =</span> <span class="st">"value"</span>, <span class="sc">-</span>diagnostico) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">fill =</span> <span class="fu">factor</span>(diagnostico))) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Informe---Trabajo-Práctico-Regresión-Logística---AyME-2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>También, descartamos la posibilidad de valores faltantes o duplicados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anyNA</span> (cmama2) <span class="co">#No hay valores faltantes</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anyDuplicated</span> (cmama2) <span class="co">#No hay elementos duplicados</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="correlación-entre-variables" class="level2">
<h2 class="anchored" data-anchor-id="correlación-entre-variables">Correlación entre variables</h2>
<p>Analizamos la correlación entre las variables independientes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cmama2 <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>diagnostico) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">corrplot</span>(<span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">type =</span> <span class="st">"upper"</span>, <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Informe---Trabajo-Práctico-Regresión-Logística---AyME-2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observamos, por ejemplo, que las variables radio, perímetro y área están altamente correlacionadas entre sí. Decidimos listar las correlaciones más altas para ver si hay alguna que sea mayor a 0.7.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cmama2 <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>diagnostico) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">"variable"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(<span class="at">key =</span> <span class="st">"variable2"</span>, <span class="at">value =</span> <span class="st">"correlacion"</span>, <span class="sc">-</span>variable) <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">variables=</span><span class="fu">paste</span>(<span class="fu">pmin</span>(variable, variable2), <span class="st">"-"</span>, <span class="fu">pmax</span>(variable, variable2)), correlacion) <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(correlacion <span class="sc">&gt;</span> <span class="fl">0.7</span>, correlacion <span class="sc">&lt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(correlacion))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                        variables correlacion
1                   perimetro_medio - radio_medio   0.9978553
2                        area_media - radio_medio   0.9873572
3                    area_media - perimetro_medio   0.9865068
4       concavidad_media - puntos_concavos_medios   0.9213910
5        compactabilidad_media - concavidad_media   0.8831207
6        perimetro_medio - puntos_concavos_medios   0.8509770
7  compactabilidad_media - puntos_concavos_medios   0.8311350
8             area_media - puntos_concavos_medios   0.8232689
9            puntos_concavos_medios - radio_medio   0.8225285
10             concavidad_media - perimetro_medio   0.7161357</code></pre>
</div>
</div>
<p>También, construimos un modelo preliminar y revisamos la variabilidad de los datos en aquellas variables que están muy correlacionadas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Diagnóstico de los datos</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span> (</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    diagnostico <span class="sc">~</span> radio_medio <span class="sc">+</span> textura_media <span class="sc">+</span> perimetro_medio <span class="sc">+</span> area_media <span class="sc">+</span> uniformidad_media <span class="sc">+</span> compactabilidad_media <span class="sc">+</span> concavidad_media <span class="sc">+</span> puntos_concavos_medios <span class="sc">+</span> simetria_media <span class="sc">+</span> dimension_fractal_media,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> cmama2</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Diagnostico: colinealidad</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span> (modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            radio_medio           textura_media         perimetro_medio 
             899.521292                1.806441              698.983071 
             area_media       uniformidad_media   compactabilidad_media 
             129.559492                4.372939               15.280847 
       concavidad_media  puntos_concavos_medios          simetria_media 
               5.259524                5.856371                1.839511 
dimension_fractal_media 
               9.787700 </code></pre>
</div>
</div>
<p>Debido a que el modelo inicial presenta variables explicativas altamente correlacionadas, buscamos un modelo que pueda explicar de manera precisa el diagnóstico en base a las medidas de tamaño, textura y forma del tumor, pero con la eliminación de aquellas variables predictoras están altamente correlacionadas y que complican la precisión y explicación del modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stepwise</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Direction:  backward/forward
Criterion:  BIC 

Start:  AIC=215.91
diagnostico ~ radio_medio + textura_media + perimetro_medio + 
    area_media + uniformidad_media + compactabilidad_media + 
    concavidad_media + puntos_concavos_medios + simetria_media + 
    dimension_fractal_media

                          Df Deviance    AIC
- compactabilidad_media    1   146.14 209.57
- perimetro_medio          1   146.15 209.59
- radio_medio              1   146.44 209.88
- dimension_fractal_media  1   146.78 210.22
- concavidad_media         1   147.23 210.67
- simetria_media           1   148.44 211.88
- area_media               1   151.63 215.06
- puntos_concavos_medios   1   151.93 215.36
- uniformidad_media        1   152.42 215.86
&lt;none&gt;                         146.13 215.91
- textura_media            1   195.34 258.78

Step:  AIC=209.57
diagnostico ~ radio_medio + textura_media + perimetro_medio + 
    area_media + uniformidad_media + concavidad_media + puntos_concavos_medios + 
    simetria_media + dimension_fractal_media

                          Df Deviance    AIC
- perimetro_medio          1   146.22 203.31
- radio_medio              1   146.52 203.62
- concavidad_media         1   147.25 204.34
- dimension_fractal_media  1   147.27 204.37
- simetria_media           1   148.46 205.56
- puntos_concavos_medios   1   151.93 209.03
- area_media               1   152.00 209.09
- uniformidad_media        1   152.45 209.55
&lt;none&gt;                         146.14 209.57
+ compactabilidad_media    1   146.13 215.91
- textura_media            1   195.48 252.57

Step:  AIC=203.31
diagnostico ~ radio_medio + textura_media + area_media + uniformidad_media + 
    concavidad_media + puntos_concavos_medios + simetria_media + 
    dimension_fractal_media

                          Df Deviance    AIC
- concavidad_media         1   147.28 198.03
- dimension_fractal_media  1   148.30 199.05
- simetria_media           1   148.52 199.27
- radio_medio              1   150.19 200.94
- puntos_concavos_medios   1   152.19 202.94
&lt;none&gt;                         146.22 203.31
- area_media               1   153.35 204.10
- uniformidad_media        1   153.39 204.14
+ perimetro_medio          1   146.14 209.57
+ compactabilidad_media    1   146.15 209.59
- textura_media            1   195.93 246.68

Step:  AIC=198.03
diagnostico ~ radio_medio + textura_media + area_media + uniformidad_media + 
    puntos_concavos_medios + simetria_media + dimension_fractal_media

                          Df Deviance    AIC
- dimension_fractal_media  1   148.38 192.79
- simetria_media           1   150.03 194.44
- radio_medio              1   153.04 197.45
- uniformidad_media        1   153.61 198.02
&lt;none&gt;                         147.28 198.03
- area_media               1   156.64 201.05
+ concavidad_media         1   146.22 203.31
+ compactabilidad_media    1   147.24 204.33
+ perimetro_medio          1   147.25 204.34
- puntos_concavos_medios   1   170.51 214.92
- textura_media            1   197.40 241.80

Step:  AIC=192.79
diagnostico ~ radio_medio + textura_media + area_media + uniformidad_media + 
    puntos_concavos_medios + simetria_media

                          Df Deviance    AIC
- simetria_media           1   150.68 188.74
- radio_medio              1   153.44 191.50
- uniformidad_media        1   154.44 192.50
&lt;none&gt;                         148.38 192.79
- area_media               1   157.38 195.44
+ dimension_fractal_media  1   147.28 198.03
+ compactabilidad_media    1   147.45 198.21
+ perimetro_medio          1   147.74 198.49
+ concavidad_media         1   148.30 199.05
- puntos_concavos_medios   1   172.31 210.38
- textura_media            1   198.83 236.89

Step:  AIC=188.74
diagnostico ~ radio_medio + textura_media + area_media + uniformidad_media + 
    puntos_concavos_medios

                          Df Deviance    AIC
- radio_medio              1   156.44 188.16
&lt;none&gt;                         150.68 188.74
- uniformidad_media        1   157.39 189.11
- area_media               1   160.32 192.04
+ simetria_media           1   148.38 192.79
+ dimension_fractal_media  1   150.03 194.44
+ concavidad_media         1   150.29 194.70
+ compactabilidad_media    1   150.33 194.74
+ perimetro_medio          1   150.37 194.77
- puntos_concavos_medios   1   180.85 212.57
- textura_media            1   199.83 231.55

Step:  AIC=188.16
diagnostico ~ textura_media + area_media + uniformidad_media + 
    puntos_concavos_medios

                          Df Deviance    AIC
- uniformidad_media        1   161.70 187.07
&lt;none&gt;                         156.44 188.16
+ radio_medio              1   150.68 188.74
+ perimetro_medio          1   151.16 189.22
+ simetria_media           1   153.44 191.50
+ concavidad_media         1   154.41 192.47
+ compactabilidad_media    1   155.78 193.84
+ dimension_fractal_media  1   156.29 194.36
- puntos_concavos_medios   1   182.53 207.90
- area_media               1   198.46 223.84
- textura_media            1   205.46 230.83

Step:  AIC=187.07
diagnostico ~ textura_media + area_media + puntos_concavos_medios

                          Df Deviance    AIC
&lt;none&gt;                         161.70 187.07
+ perimetro_medio          1   156.26 187.98
+ uniformidad_media        1   156.44 188.16
+ radio_medio              1   157.39 189.11
+ simetria_media           1   157.81 189.53
+ compactabilidad_media    1   160.95 192.67
+ dimension_fractal_media  1   161.64 193.36
+ concavidad_media         1   161.64 193.36
- area_media               1   203.34 222.37
- textura_media            1   205.78 224.81
- puntos_concavos_medios   1   288.98 308.01</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = diagnostico ~ textura_media + area_media + puntos_concavos_medios, 
    family = binomial(link = "logit"), data = cmama2)

Coefficients:
           (Intercept)           textura_media              area_media  
            -16.748069                0.325463                0.007776  
puntos_concavos_medios  
            101.603693  

Degrees of Freedom: 568 Total (i.e. Null);  565 Residual
Null Deviance:      751.4 
Residual Deviance: 161.7    AIC: 169.7</code></pre>
</div>
</div>
</section>
<section id="postulación-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="postulación-del-modelo">Postulación del modelo</h2>
<p>Así, se arriba a un modelo más sencillo, más preciso y que explica mejor el criterio de diagnóstico en base a las medidas del tamaño, la textura y la forma del tumor, mediante el criterio de información de Akkaike</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>cmama3 <span class="ot">&lt;-</span> cmama2[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">9</span>)]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>modelo_aic <span class="ot">&lt;-</span> <span class="fu">glm</span>(diagnostico <span class="sc">~</span> ., <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), cmama3)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_aic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diagnostico ~ ., family = binomial(link = "logit"), 
    data = cmama3)

Coefficients:
                         Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)            -16.748069   1.922261  -8.713  &lt; 2e-16 ***
textura_media            0.325463   0.055660   5.847 4.99e-09 ***
area_media               0.007776   0.001451   5.359 8.37e-08 ***
puntos_concavos_medios 101.603693  13.126390   7.740 9.91e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 751.44  on 568  degrees of freedom
Residual deviance: 161.70  on 565  degrees of freedom
AIC: 169.7

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
</section>
<section id="verificación-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="verificación-del-modelo">Verificación del modelo</h2>
<p>Verificamos que el factor de inflación de la varianza (VIF) de cada variable sea menor a 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_aic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         textura_media             area_media puntos_concavos_medios 
              1.361215               1.044589               1.313795 </code></pre>
</div>
</div>
</section>
<section id="interpretación-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="interpretación-del-modelo">Interpretación del modelo</h2>
<p>Coeficientes e intervalos de confianza para cada variable predictora.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="fu">coef</span>(modelo_aic),<span class="fu">confint.default</span>(modelo_aic)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           2.5 %       97.5 %
(Intercept)            5.326061e-08 1.230763e-09 2.304825e-06
textura_media          1.384671e+00 1.241564e+00 1.544274e+00
area_media             1.007807e+00 1.004944e+00 1.010677e+00
puntos_concavos_medios 1.336359e+44 8.968494e+32 1.991255e+55</code></pre>
</div>
</div>
<p>Por cada aumento en una unidad de la textura media del tumor, se estima que la chance de que el diagnóstico del tumor sea maligno aumenta entre <span class="math inline">\(1.242\)</span> y <span class="math inline">\(1.544\)</span>.</p>
<p>Por cada aumento en una unidad del área media del tumor, se estima que la chance de que el diagnóstico del tumor sea maligno aumenta entre <span class="math inline">\(1.005\)</span> y <span class="math inline">\(1.011\)</span>.</p>
<p>Por cada aumento en una unidad de la cantidad de puntos cóncavos medios del tumor, se estima que la chance de que el diagnóstico sea que el tumor sea maligno aumenta entre <span class="math inline">\(8.968 \times 10^{32}\)</span> y <span class="math inline">\(1.991 \times 10^{55}\)</span>.</p>
</section>
<section id="pseudo-r2" class="level2">
<h2 class="anchored" data-anchor-id="pseudo-r2">Pseudo <span class="math inline">\(R^2\)</span></h2>
<p>Se mide la reducción proporcional de la variación en el criterio de Diagnóstico al utilizar las variables de Textura, Área y Puntos Cóncavos medios. El coeficiente de determinación <span class="math inline">\(R^2\)</span> de Nagelkerke suele ser más bajo que el coeficiente de determinación de <span class="math inline">\(R^2\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PseudoR2</span>(modelo_aic, <span class="at">which =</span> <span class="fu">c</span>(<span class="st">"Nagelkerke"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nagelkerke 
 0.8803015 </code></pre>
</div>
</div>
<p>Por lo tanto, hay una reducción del 88% de la variación en el criterio de Diagnóstico</p>
</section>
<section id="prueba-de-bondad-de-ajuste-hosmer-lemeshow" class="level2">
<h2 class="anchored" data-anchor-id="prueba-de-bondad-de-ajuste-hosmer-lemeshow">Prueba de Bondad de Ajuste Hosmer-Lemeshow</h2>
<p>Se realiza una prueba de bondad de ajuste del modelo de regresión logística.</p>
<p>La hipótesis nula es que el modelo está bien ajustado</p>
<p>Y la hipótesis alternativa es que no lo está.</p>
<p>El estadístico de la prueba es el Chi-Cuadrado de Pearson con nivel de significancia de 0.95 y 10 (clases) - 2 grados de libertad</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">HosmerLemeshowTest</span>(<span class="at">fit =</span> <span class="fu">fitted</span>(modelo_aic), <span class="at">obs =</span> cmama3<span class="sc">$</span>diagnostico)<span class="sc">$</span>C</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer-Lemeshow C statistic

data:  fitted(modelo_aic) and cmama3$diagnostico
X-squared = 3.4834, df = 8, p-value = 0.9005</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creación curva de densidad</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fl">3.4834</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dchisq</span>(x, <span class="dv">8</span>), <span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">40</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">'Prueba de Bondad de Ajuste Hosmer-Lemeshow (gl = 8)'</span>, <span class="at">xlab =</span> <span class="st">'Estadístico C'</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">'Densidad de Probabilidad'</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Crear vector de valores chi teoricos</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>x_teor <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">8</span>), <span class="dv">40</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Crear vector de p-Valor</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>p_vector <span class="ot">&lt;-</span> <span class="fu">dchisq</span>(x_teor, <span class="dv">8</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Rellenado</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(x_teor, <span class="fu">rev</span>(x_teor)), <span class="fu">c</span>(p_vector, <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(p_vector))),</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">'red'</span>, <span class="at">alpha=</span><span class="fl">0.3</span>), <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="co">#Crear vector de valor observado</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>x_obs <span class="ot">&lt;-</span> <span class="fu">seq</span>(x, <span class="dv">40</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Crear vector de p-Valor</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>p_vector <span class="ot">&lt;-</span> <span class="fu">dchisq</span>(x_obs, <span class="dv">8</span>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a><span class="co">#Rellenado</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(x_obs, <span class="fu">rev</span>(x_obs)), <span class="fu">c</span>(p_vector, <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(p_vector))),</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">'green'</span>, <span class="at">alpha=</span><span class="fl">0.3</span>), <span class="at">border =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Informe---Trabajo-Práctico-Regresión-Logística---AyME-2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La prueba de hipótesis no rechaza la hipótesis nula.</p>
<p>Por lo tanto, el modelo de regresión logística está bien ajustado.</p>
</section>
<section id="predicción-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="predicción-del-modelo">Predicción del modelo</h2>
<p>Predicción de la probabilidad de que el tumor sea maligno.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>referencia <span class="ot">&lt;-</span> cmama3<span class="sc">$</span>diagnostico</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>prediccion <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_aic, <span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Curva ROC y área bajo la curva ROC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>curva <span class="ot">&lt;-</span> <span class="fu">roc</span>(referencia, prediccion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">-</span>curva<span class="sc">$</span>specificities, curva<span class="sc">$</span>sensitivities, <span class="at">type=</span><span class="st">"l"</span>,<span class="at">xlab=</span><span class="st">"1-Especificidad"</span>,<span class="at">ylab=</span><span class="st">"Sensibilidad"</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">"blue"</span>,<span class="at">xaxs=</span><span class="st">"i"</span>,<span class="at">yaxs=</span><span class="st">"i"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Informe---Trabajo-Práctico-Regresión-Logística---AyME-2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Area bajo la curva ROC</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>(areaRoc<span class="ot">&lt;-</span><span class="fu">auc</span>(referencia, prediccion)); <span class="fu">ci</span>(areaRoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1
Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.9862</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>95% CI: 0.9794-0.993 (DeLong)</code></pre>
</div>
</div>
<p>Corte óptimo de la curva ROC</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>(opt <span class="ot">&lt;-</span> <span class="fu">coords</span>(curva, <span class="st">"best"</span>, <span class="at">ret=</span><span class="fu">c</span>(<span class="st">"threshold"</span>, <span class="st">"specificity"</span>, <span class="st">"sensitivity"</span>, <span class="st">"accuracy"</span>,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"tn"</span>, <span class="st">"tp"</span>, <span class="st">"fn"</span>, <span class="st">"fp"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          threshold specificity sensitivity  accuracy  tn  tp fn fp
threshold 0.4540945   0.9579832   0.9150943 0.9420035 342 194 18 15</code></pre>
</div>
</div>
<p>Tabla de clasificación</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Según corte óptimo de corte por Youden</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>prediccion_clases <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(prediccion <span class="sc">&gt;</span> opt<span class="sc">$</span>threshold, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> <span class="fu">factor</span>(prediccion_clases), <span class="at">reference =</span> <span class="fu">factor</span>(cmama3<span class="sc">$</span>diagnostico), <span class="at">positive =</span> <span class="st">"1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 342  18
         1  15 194
                                          
               Accuracy : 0.942           
                 95% CI : (0.9195, 0.9597)
    No Information Rate : 0.6274          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.8756          
                                          
 Mcnemar's Test P-Value : 0.7277          
                                          
            Sensitivity : 0.9151          
            Specificity : 0.9580          
         Pos Pred Value : 0.9282          
         Neg Pred Value : 0.9500          
             Prevalence : 0.3726          
         Detection Rate : 0.3409          
   Detection Prevalence : 0.3673          
      Balanced Accuracy : 0.9365          
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<p>En resumen, se calculó el mejor punto de corte [<em>cut-off</em> o <em>threshold</em>], cuya precisión es de <span class="math inline">\(0.454\)</span>. Esto significa que si la chance de un posible tumor maligno observado sea mayor que <span class="math inline">\(0.454\)</span>, entonces se decide por un diagnóstico de <em>tumor maligno</em> de cáncer de mama. Pero si la chance es menor o igual que <span class="math inline">\(0.454\)</span>, entonces se decide por un diagnóstico de <em>tumor benigno</em>.</p>
<p>Además, la sensibilidad [<em>sensitivity</em>] es de <span class="math inline">\(0.915\)</span>. Esto significa que la probabilidad de decidir en forma adecuada por un diagnóstico de <em>tumor maligno</em> y cáncer de mama es de <span class="math inline">\(0.915\)</span>. Y la especificidad [<em>specificity</em>] de <span class="math inline">\(0.958\)</span> significa que la probabilidad de decidir de manera correcta por un diagnóstico de <em>tumor benigno</em> es de <span class="math inline">\(0.958\)</span>.</p>
</section>
<section id="conclusión" class="level2">
<h2 class="anchored" data-anchor-id="conclusión">Conclusión</h2>
<p>A partir del análisis realizado, se concluye que el criterio de diagnóstico de tumor maligno se ve explicado de manera significativa por la forma del tumor y, en particular, por la observación y modelado de concavidades en el tumor. También, se obtuvo un criterio de decisión de diagnóstico en el que se decide de manera acertada por un diagnóstico de tumor maligno en el 91.5% de los casos y po un diagnóstico de tumor benigno acertado en el 95.8% de los casos.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>