---
title: "Informe - Trabajo Práctico Regresión Logística - AyME"
author: ""
format: html
editor: visual
---

# Cáncer de mama

## Introducción (La armamos al final de la redacción del cuerpo y la conclusión)

## Análisis previo de las variables de la base de datos

Para comenzar, se supone que la investigación sobre las células de cáncer de mama no es un experimento controlado, por lo que es necesario analizar la relación entre las variables que pueden ser fundamentales para explicar y comunicar si el diagnóstico de un tumor es benigno o maligno, y descartar las variables más complejas de comunicar y que requieren conocimientos especializados en el tema.

Entonces, las variables que se mantienen son:

-   Diagnóstico
-   Radio medio
-   Perímetro medio
-   Simetría media

Y para mantener un modelo sencillo, explicable y comunicable, se descartan las variables que requieren una comprensión más precisa o especializada del tema, que son:

-   Textura media
-   Superficie media
-   Suavidad media
-   Compactado medio
-   Concavidad media
-   Puntos cóncavos medios
-   Dimensión Fractal Media
-   Todas las variables que son errores estándar
-   Todas las variables que son "peores valores"
-   La trigésimatercera variable $X$ por no contener información

## Análisis exploratorio y postulación de un modelo

### Análisis exploratorio

```{r}

```

### Postulación de un modelo

# Sueño

## Introducción (la redactamos al final de la redacción del cuerpo y la conclusión)

##Análisis previo de las variables de la base de datos
